apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Values.DeploymentName }}
  namespace: {{ .Values.NamespaceName }}
  labels:
    {{- toYaml .Values.labelsDeployment | nindent 4 }}
spec:
  selector:
    matchLabels:
       {{- toYaml .Values.matchLabels | nindent 6 }}
  replicas: 2
  template:
    metadata:
      labels:
         {{- toYaml .Values.labels | nindent 8 }}
    spec:
      containers:
      - name:  {{ .Values.containers.name }}
        image:  {{ .Values.containers.image }}
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 300m
            memory: 256Mi
