name: Merge

on:
  push:
    branches:
      - main

jobs:


  test:
    name: '🚀Test'
    runs-on: ubuntu-latest
    steps:
      - id: message
        name: Generate message Test
        run: |
             echo "ejecutando los test"

  build:
    needs: 'test'
    name: '🚀Build'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Generate message Build
      run: |
             git_hash=$(git rev-parse --short "$GITHUB_SHA")
             echo $git_hash

  # docker:
  #   needs: [ test, build ]
  #   name: '🚀Docker Hub'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - id: sets-a-secret
  #       name: Generate, mask, and output a secret
  #       run: |
  #           the_secret=$((RANDOM))
  #           echo "secret-number=$the_secret" >> "$GITHUB_OUTPUT"
  #       name: Checkout
  #       uses: actions/checkout@v3
  #     -
  #       name: Set up QEMU
  #       uses: docker/setup-qemu-action@v2
  #     -
  #       name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v2
  #     -
  #       name: Download repository
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: artifact
  #     -
  #       name: Login to Docker Hub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USER }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #     -
  #       name: Build and push
  #       uses: docker/build-push-action@v4
  #       with:
  #         context: .
  #         platforms: linux/amd64,linux/arm64
  #         push: true
  #         file: Dockerfile
  #         tags: ${{ secrets.DOCKERHUB_USER }}/backend:${{ steps.sets-a-secret.outputs.secret-number }}